services:
  postgres-db : 
    image : postgres:15
    environment :
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : postgres
      POSTGRES_DB : postgres
    healthcheck :
      test : ["CMD-SHELL", "pg_isready -U postgres"]
      interval : 5s
      retries : 5
      start_period : 10s
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./data/demo-small-en.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"


  superset:
    build:
      context: ./visualisation/superset
      dockerfile: Dockerfile
    container_name: superset
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@superset.com
      - ADMIN_PASSWORD=admin
      - LOAD_EXAMPLES=yes
    ports:
      - '8088:8088'
    volumes:
      - ./visualisation/superset/superset_config.py:/app/superset_config.py

volumes:
  postgres-db-volume: