[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "plotly>=6.3.1",
    "polars>=1.34.0",
    "requests>=2.32.5",
]
